export function formatPrice(cents) {
  return (cents / 100).toLocaleString('en-GB', {
    style: 'currency',
    currency: 'GBP'
  });
}

export function rando(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

export function slugify(text) {
  return text
    .toString()
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^\w-]+/g, '')
    .replace(/--+/g, '-')
    .replace(/^-+/, '')
    .replace(/-+$/, '');
}

export function getFunName() {
  const adjectives = [
    'acclaimed',
    'affordable',
    'air',
    'american',
    'asian',
    'best',
    'better',
    'casual',
    'celebrated',
    'certain',
    'charming',
    'cheap',
    'chic',
    'chinese',
    'class',
    'crowded',
    'decent',
    'different',
    'down',
    'downtown',
    'elegant',
    'end',
    'ethnic',
    'even',
    'excellent',
    'exclusive',
    'expensive',
    'fabulous',
    'famous',
    'fanciest',
    'fancy',
    'fashionable',
    'favorite',
    'few',
    'fine',
    'finer',
    'finest',
    'first',
    'food',
    'foreign',
    'formal',
    'french',
    'friendly',
    'german',
    'good',
    'great',
    'greek',
    'hottest',
    'in',
    'independent',
    'indian',
    'inexpensive',
    'interesting',
    'international',
    'italian',
    'japanese',
    'known',
    'korean',
    'kosher',
    'large',
    'larger',
    'leading',
    'little',
    'local',
    'major',
    'many',
    'mexican',
    'more',
    'most',
    'multiple',
    'nearby',
    'new',
    'nice',
    'nicer',
    'nicest',
    'night',
    'notch',
    'numerous',
    'oldest',
    'only',
    'other',
    'outdoor',
    'outstanding',
    'own',
    'owned',
    'parisian',
    'popular',
    'posh',
    'priced',
    'pricey',
    'public',
    'quality',
    'rate',
    'renowned',
    'romantic',
    'run',
    'same',
    'service',
    'several',
    'simple',
    'site',
    'small',
    'smart',
    'sophisticated',
    'spanish',

    'star',
    'style',
    'stylish',
    'successful',
    'such',
    'superb',
    'themed',
    'top',
    'traditional',
    'trendy',
    'upscale',
    'various',
    'vegetarian',
    'vietnamese',
    'wonderful'
  ];

  const nouns = [
    'cafe',
    'hotel',
    'dining room',
    'inn',
    'coffee shop',
    'sandwich shop',
    'tavern',
    'pub',
    'steakhouse',
    'coffee house',
    'chophouse',
    'tearoom',
    'luncheon',
    'luncheonette',
    'lunch-wagon',
    'hamburger stand',
    'fast-food outlet',
    'fast-food joint',
    'fast-food place',
    'trattoria',
    'ristorante',
    'estaminet',
    'bistro',
    'brasserie',
    'creamery',
    'dining car',
    'dining coach',
    'dining saloon',
    'diner',
    'lunch bar',
    'soda fountain',
    'milk bar',
    'hot-dog stand',
    'snack bar',
    'raw bar',
    'sushi bar',
    'automat',
    'rathskeller',
    'rotisserie',
    'cabaret',
    'night club',
    'cafeteria',
    'grill',
    'grillroom',
    'oyster house',
    'barbecue',
    'spaghetti house',
    'deli',
    'pizzeria',
    'canteen'
  ];

  return `${rando(adjectives)}-${rando(adjectives)}-${rando(nouns)}`;
}
